<?php
namespace samsonframework\html2less\tests;

use samsonframework\html2less\Tree;

/**
 * Created by <egorov@samsonos.com>
 * on 18.04.16 at 17:20
 */
class TreeTest extends \PHPUnit_Framework_TestCase
{
    /** @var Tree */
    protected $lessTree;

    /** Init tests */
    public function setUp()
    {
        $this->lessTree = new Tree();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testTagGroupingAtSameLevel()
    {
        // HTML code block
        $html = <<<'HTML'
    <div id="testDIVIdentifier" class="test-class">
        <a><span>Test link</span></a>
        <a id="testAIdentifier"><span>Test link 2</span></a>
        <a><span>Test link 3</span></a>
        <a id="testAIdentifier2"><span id="testSPANIdentifier">Test link 4</span></a>
    </div>
HTML;

        $expected = <<<'LESS'
{
  #testDIVIdentifier{
    &.test-class{
    }
    a{
      &#testAIdentifier{
        span{
        }
      }
      &#testAIdentifier2{
        #testSPANIdentifier{
        }
      }
    }
  }
}

LESS;

        $tree = new Tree();
        $lessTree = $tree->build($html);
        $output = $tree->output($lessTree);
        $this->assertEquals($expected, $output);
    }
}
